#!/usr/bin/python
import re, sys
filename = sys.argv[1]
users = {}
with open(filename) as f:
  lines = f.readlines()
  num = int(lines[0])
  #print num, len(lines)
  i = 1
  while i < len(lines):
    line = lines[i].strip()
    user = re.split('\s+',line)
    username = user[0].strip()
    #print i, user[1]
    #print user[1]
    if not users.has_key(username):
            users[username] = "T"
    #print user
    for j in range(int(user[1])):
            i+= 1
            u = lines[i].strip()
            if users[username] == "T":
                    users[u] = "L"
            else:
                    users[u] = "T"
    i+=1

#print users
L= 0
T = 0
for k,v in users.items():
	if v == "L": 
		L += 1
	else:
		T += 1

print "%s %s"%tuple(sorted([L,T],reverse=True))
