#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

from thrift.Thrift import *

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class Color:
  RED = 1
  YELLOW = 2
  GREEN = 3
  BLUE = 4

  _VALUES_TO_NAMES = {
    1: "RED",
    2: "YELLOW",
    3: "GREEN",
    4: "BLUE",
  }

  _NAMES_TO_VALUES = {
    "RED": 1,
    "YELLOW": 2,
    "GREEN": 3,
    "BLUE": 4,
  }

